name: seattle-flu
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bcftools
  - bowtie2
  - curl
  - ncurses=6.1
  - picard
  - python=3.6
  - samtools
  - snakemake
  - tabix
  - trimmomatic
  - varscan
  - vcftools
